apiVersion: apps/v1
kind: Deployment
metadata:
  name: SampleOperator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: SampleOperator
  template:
    metadata:
      labels:
        name: SampleOperator
    spec:
      serviceAccountName: SampleOperator
      containers:
        - name: SampleOperator
          # Replace this with the built image name
          image: REPLACE_IMAGE
          command:
          - SampleOperator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "SampleOperator"
