kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: SampleOperator
subjects:
- kind: ServiceAccount
  name: SampleOperator
roleRef:
  kind: Role
  name: SampleOperator
  apiGroup: rbac.authorization.k8s.io
