apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: jenkins-st-demo
spec:
  serviceName: "st-svc"
  replicas: 2
  selector:
    matchLabels:
       app: jenkins-app-st
  template:
     metadata:
       labels:
         app: jenkins-app-st
     spec:
       containers:
       - name: jenkins-app-container
         image: raju140/jenkins
         ports:
         - containerPort: 8080
         - containerPort: 50000
         volumeMounts:
          - mountPath: "/var/jenkins_home"
            name: local-volume
  volumeClaimTemplates:
  - metadata:
      name: local-volume
    spec:
     accessModes:
        - ReadWriteOnce
     storageClassName: manual
     resources:
        requests:
           storage: 500Mi
