apiVersion: v1
kind: ConfigMap
metadata:
  name: static-files
  #namespace: hello-deploy
data:
  index.html: |
       <html><head><title>pramati technologies pvt ltd.</title></head>
       <body><h1>Welcome to Pramati Technologies Pvt Ltd.</h1>
       <p>
        Hyderabad.</p>
       </body></html>
 
