apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
  #namespace: hello-deploy
data:
  default.conf: |
    server {
      listen                  600;
      server_name             _;
      index index.html index.htm index.nginx-debian.html;
      root                    /usr/share/nginx/html;
      location / {
        try_files $uri $uri/ =404;
      }
    }
     

