apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "angularapp.fullname" . }}-local-volume
  labels:
    type: {{ .Values.pv.type }}
spec:
  storageClassName: {{ .Values.pv.spec.storageClassName }}
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: {{ .Values.pv.spec.hostPath | quote}}