apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "angularapp.fullname" . }}-local-volume-pvc
spec:
  storageClassName: {{.Values.pv.spec.storageClassName}}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi