apiVersion: v1
kind: Service
metadata:
  name: {{ include "angularapp.fullname" . }}
  labels:
    {{- include "angularapp.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      nodePort: {{ .Values.service.nodePort}}
      name: http
  externalIPs:
    - {{ .Values.service.externalIPs}}
  selector:
    {{- include "angularapp.selectorLabels" . | nindent 4 }}
